<?php
session_start();$u=getenv('ADMIN_USER')?:'admin';$p=getenv('ADMIN_PASS')?:'CHANGE-ME';
$db=new PDO('sqlite:'.__DIR__.'/wasla.sqlite');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$db->exec("CREATE TABLE IF NOT EXISTS applicants(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,age INTEGER,city TEXT,contact TEXT,bio TEXT,status TEXT DEFAULT 'جديد',created_at TEXT)");
if(isset($_GET['logout'])){session_destroy();header('Location:/admin.php');exit;}
if(!isset($_SESSION['admin'])){if($_SERVER['REQUEST_METHOD']==='POST'&&hash_equals($u,$_POST['user']??'')&&hash_equals($p,$_POST['pass']??'')){$_SESSION['admin']=1;header('Location:/admin.php');exit;}?>
<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin</title><style>body{background:#100b12;color:#fff;font-family:Tahoma;padding:30px}.box{max-width:400px;margin:10vh auto;padding:25px;background:#ffffff0b;border-radius:20px}input,button{width:100%;padding:13px;margin:8px 0;box-sizing:border-box}button{background:#e82f6a;color:#fff;border:0;border-radius:10px}</style><div class=box><h1>NJA-WASLA</h1><h2>دخول الإدارة</h2><form method=post><input name=user placeholder="اسم المستخدم" required><input name=pass type=password placeholder="كلمة المرور" required><button>دخول</button></form></div><?php exit;}
if(isset($_POST['delete'])){$s=$db->prepare('DELETE FROM applicants WHERE id=?');$s->execute([(int)$_POST['delete']]);header('Location:/admin.php');exit;}
$rows=$db->query('SELECT * FROM applicants ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);
function e($x){return htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>صندوق الطلبات</title><style>body{background:#100b12;color:#fff;font-family:Tahoma;padding:20px}main{max-width:1000px;margin:auto}.card{background:#ffffff0b;border:1px solid #ffffff18;border-radius:18px;padding:20px;margin:12px 0}.top{display:flex;justify-content:space-between}.danger{background:#7a193d;color:#fff;border:0;padding:10px;border-radius:8px}a{color:#ff6c95}</style><main><p><a href="?logout=1">خروج</a></p><h1>NJA-WASLA — صندوق الطلبات</h1><?php foreach($rows as $a):?><article class=card><div class=top><h2><?=e($a['name'])?></h2><b><?=e($a['status'])?></b></div><p>العمر: <?=e($a['age'])?> — المدينة: <?=e($a['city'])?></p><p>التواصل: <?=e($a['contact'])?></p><p>النبذة: <?=nl2br(e($a['bio']))?></p><small><?=e($a['created_at'])?></small><form method=post><button class=danger name=delete value="<?=e($a['id'])?>" onclick="return confirm('حذف الطلب؟')">حذف</button><button type=button onclick="print()">طباعة / PDF</button></form></article><?php endforeach;if(!$rows)echo'<div class=card>لا توجد طلبات حتى الآن.</div>';?></main>